@startuml callflow
skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
    AttributeIconSize 0
}
'skinparam style strictuml
skinparam stereotypeCBackgroundColor White
skinparam stereotypeIBackgroundColor White
skinparam stereotypeEBackgroundColor White
skinparam stereotypeABackgroundColor White
skinparam linetype ortho

title "Basic Flow 1-to-1 (PUBSUB))"
hide footbox

actor A
actor B

collections MsgSrv1
collections MsgSrv2
database DB
queue PUBSUB

A -> MsgSrv1 : connect
MsgSrv1 -> DB : location A
MsgSrv1 -> PUBSUB : SUBSCRIBE A


B -> MsgSrv2 : connect
MsgSrv2 -> DB : location B
MsgSrv2 -> PUBSUB : SUBSCRIBE B


A -> MsgSrv1 : "msg" B
MsgSrv1 -> DB ++ : Is B connected?
return yes


MsgSrv1 -> PUBSUB : PUBLISH B "msg"

PUBSUB -> MsgSrv2 : "msg"

MsgSrv2 -> B : "msg"

@enduml


