@startuml callflow
skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
    AttributeIconSize 0
}
'skinparam style strictuml
skinparam stereotypeCBackgroundColor White
skinparam stereotypeIBackgroundColor White
skinparam stereotypeEBackgroundColor White
skinparam stereotypeABackgroundColor White
skinparam linetype ortho

title "Basic Flow 1-to-1 (PUBSUB))"
hide footbox

actor A
actor B

collections MsgSrv1
collections MsgSrv2
database DB

queue REDIS_A AS RD1
queue REDIS_B AS RD2

database DYNAMO

A -> MsgSrv1 : connect
MsgSrv1 -> RD1 : SUBSCRIBE A

MsgSrv1 -> DB : save REDIS A addr.


B -> MsgSrv2 : connect
MsgSrv2 -> RD2 : SUBSCRIBE B

MsgSrv2 -> DB : save REDIS B addr.


A -> MsgSrv1 : "msg" B
MsgSrv1 -> DB ++ : Is B connected?
return addr. of REDIS


MsgSrv1 -> RD2 : PUBLISH B "msg"

RD2 -> MsgSrv2 : "msg"

MsgSrv2 -> B : "msg"

@enduml


