@startuml callflow
skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
    AttributeIconSize 0
}
'skinparam style strictuml
skinparam stereotypeCBackgroundColor White
skinparam stereotypeIBackgroundColor White
skinparam stereotypeEBackgroundColor White
skinparam stereotypeABackgroundColor White
skinparam linetype ortho

'title "Basic Flow 1-to-1 (PUBSUB))"
hide footbox

actor A
actor B

collections IM1
collections IM2

queue REDIS AS RD

database DYNAMO

A -> IM1 : connect
IM1 -> RD : SUBSCRIBE A

B -> IM2 !!: connect

A -> IM1 : "msg" to B
IM1 -> DYNAMO : store "msg"

IM1 -> RD !!: PUBLISH B "msg"

IM1 -> PUSH : wake-up

PUSH -> B : wake-up

B -> B : offline->online

B -> IM2 : connect

IM2 -> DYNAMO: retrieve stored message

DYNAMO -> IM2 : "msg"

IM2 -> B : "msg"

B -> IM2 : "delivery"

IM2 -> DYNAMO : delete "msg" 


@enduml


