@startuml messageFlow-online
skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
    AttributeIconSize 0
}
'skinparam style strictuml
skinparam stereotypeCBackgroundColor White
skinparam stereotypeIBackgroundColor White
skinparam stereotypeEBackgroundColor White
skinparam stereotypeABackgroundColor White
skinparam linetype ortho

title "Message Flow - online"
hide footbox

actor A
actor B

collections MsgSrvA
collections MsgSrvB
queue Redis
database DB 

MsgSrvB -> Redis : SUBSCRIBE chat-id

A -> MsgSrvA : "msg"

MsgSrvA -> DB : Write "msg"

MsgSrvA -> Redis : SET msg-id "msg"


MsgSrvA -> MsgSrvA : Is B subscribing chat-id?

MsgSrvA -> Redis : PUBLISH chat-id "msg-id"

Redis -> MsgSrvB : "msg-id"

MsgSrvB -> Redis ++ : GET msg-id
return "msg"

MsgSrvB -> B : Receive "msg"


@enduml


