@startuml callflow
skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
    AttributeIconSize 0
}
'skinparam style strictuml
skinparam stereotypeCBackgroundColor White
skinparam stereotypeIBackgroundColor White
skinparam stereotypeEBackgroundColor White
skinparam stereotypeABackgroundColor White
skinparam linetype ortho

title "Joining"
hide footbox

actor A
actor B

collections MsgSrv1
collections MsgSrv2
queue PUBSUB

A -> MsgSrv1 : connect
MsgSrv1 -> DB : location A

B -> MsgSrv2 : connect
MsgSrv2 -> DB : location B

A -> MsgSrv1 ++ : Create (A,B)

MsgSrv1 -> MsgSrv1 : chat-id ?

create control Go As Go1

MsgSrv1 -> Go1 : Join chat-id
Go1 -> PUBSUB : SUBS chat-id

MsgSrv1 -> DB ++ : where B?
return location B

MsgSrv1 -> MsgSrv2 ++ : Join B, chat-id

create control Go As Go2

MsgSrv2 -> Go2 : Join B, chat-id
Go2 -> PUBSUB : SUBS chat-id

return 200 OK

return chat-id

@enduml


