@startuml callflow
skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
    AttributeIconSize 0
}
'skinparam style strictuml
skinparam stereotypeCBackgroundColor White
skinparam stereotypeIBackgroundColor White
skinparam stereotypeEBackgroundColor White
skinparam stereotypeABackgroundColor White
skinparam linetype ortho

'title "Basic Flow 1-to-1 (PUBSUB))"
hide footbox

actor A
actor B

collections IM1
collections IM2

queue PUBSUB AS RD

queue QUEUE AS DB

A -> IM1 : connect
IM1 -> RD : SUBSCRIBE A

B -> IM2 !! : connect (failed)

A -> IM1 : "msg" to B

IM1 -> IM1 : Is B online?

IM1 -> DB : store "msg" (RPUSH B "msg")

B -> B : offline->online

B -> IM2 : connect

IM2 -> RD : SUBSCRIBE B

IM2 -> DB : check messages (LRANGE 0 -1)

DB -> IM2 : "msg"

IM2 -> B : "msg"

B -> IM2 : "delivery"


IM2 -> RD : PUBLISH A "delivery"

RD -> IM1 : "delivery"

IM1 -> A : "delivery"


B -> B : read "msg"

B -> IM2 : "display"


IM2 -> RD : PUBLISH A "display"

RD -> IM1 : "display"

IM1 -> A : "display"


@enduml


